CREATE DATABASE [MyAppTest]  ON (NAME = 'MyAppTest', FILENAME = '{0}') COLLATE Persian_100_CI_AS
ALTER DATABASE [MyAppTest] SET ALLOW_SNAPSHOT_ISOLATION ON;
ALTER DATABASE[MyAppTest] SET READ_COMMITTED_SNAPSHOT ON;